# Generated by Django 2.2.3 on 2019-07-16 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('article', 'article'), ('video', 'video'), ('course', 'course'), ('docs', 'docs')], max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(to='app.tag')),
            ],
        ),
    ]
