# Generated by Django 2.2.3 on 2019-08-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='category',
            field=models.CharField(choices=[('article', 'article'), ('video', 'video'), ('course', 'course'), ('docs', 'docs'), ('book', 'book'), ('cheatsheet', 'cheatsheet')], max_length=200),
        ),
    ]
