# Generated by Django 2.2 on 2020-02-18 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200217_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='total_hit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
        migrations.CreateModel(
            name='TutorialHitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Tutorial')),
            ],
        ),
    ]
